#!/bin/sh

#
# depends on gist
#

# CONSTANTS
# pacman native list gist file name
PACNAT_FILE="$(hostname).pacnative-list.pkg"
# aur list gist file name
AUR_FILE="$(hostname).aur-list.pkg"
# base working path
DESTDIR="$1"

help() {
  # show help text
  # config usage
  printf "You need to manually run this script at least once after each install to configure the hook/script. It will ask you for a github access token with gist permissions. If you don't have one, this script can create one for you if you provide your login credentials (they will not be saved anywhere and will only be used to create the said access token).\nYou can also remove the created .gist file to trigger a reconfiguration on the next run of this script.\n"
  # flags
  printf " -h, -H, --help, -help    Show this help page\n"
  printf " -s, -u [p, a, b]         Get [p]acman, [a]ur or [b]oth (default is pacman)\n"
  printf "If you installed this using a different 'DESTDIR' on the Makefile, you might want to pass the path to the used 'DESTDIR' to this script as the last argument.\n"
  exit 0
}

get_pkg() {
  # check for gists' ids file existance
  if ! test -r "$DESTDIR/etc/pbg"; then
    printf "No gists' ids file file found.\n"
    exit 1
  fi

  # get list of pacman natives
  if [ "$1" != "a" ]; then
    printf "%s\n" "$(gist -r "$(head -n 1 "$DESTDIR/etc/pbg")")"
  fi

  # get list of AUR packages
  if [ "$1" = "a" ] || [ "$1" = "b" ]; then
    printf "%s\n" "$(gist -r "$(tail -n 1 "$DESTDIR/etc/pbg")")"
  fi
  
  exit 0
}

cargs() {
  case "$1" in
    "-h" | "-H" | "-help" | "--help")
      # show help if asked
      help
      ;;
    "-s" | "-u")
      # check if valid options were given
      if [ "$2" != "p" ] && [ "$2" != "b" ] && [ "$2" != "a" ] && [ "$2" ]; then
        printf "%s is not a valid option for -s/-u" "$2"
        exit 1
      fi
      # set base path (if needed)
      DESTDIR="$3"
      # get packages
      get_pkg "$2"
      ;;
    -*)
      printf "%s is not a known flag\n" "$1"
      exit 1
      ;;
    *)
      printf "pbg: starting\n"
      ;;
  esac
}

new_pbg() {
  # create gists
  gist_nat="$(pacman -Qqen | gist -p -f "$PACNAT_FILE" -d 'Pacman package list.')"
  gist_aur="$(pacman -Qqem | gist -p -f "$AUR_FILE" -d 'AUR package list.')"

  # save created gists' ids
  printf "%s\n" "$gist_nat" | sed 's/https:\/\/gist.github.com\///g' > "$DESTDIR/etc/pbg"
  printf "%s" "$gist_aur" | sed 's/https:\/\/gist.github.com\///g' >> "$DESTDIR/etc/pbg"
  chmod 644 "$DESTDIR/etc/pbg"
}

init() {
  # check if the gist access token exists
  if ! test -r "$DESTDIR/root/.gist"; then
    printf "No gist access token found or not readable.\nDo you wish to provide an access token yourself? [Y/n] "
    read ans
    if [ ! "$ans" ] || [ "$ans" == "Y" ] || [ "$ans" == "y" ]; then
      # read token from user
      ! read token && exit 1
      printf "%s" "$token" > "$DESTDIR/root/.gist"
    else
      # use gist to create token for user
      printf "Gist can generate the token for you.\n"
      ! gist --login && exit 1
    fi
  fi

  # copy user's gist access token to root
  if ! cmp --silent ~/.gist "$DESTDIR/root/.gist"; then
    cp "$HOME/.gist" "$DESTDIR/root/.gist";
  fi

  # create new pbg file
  new_pbg
}

update() {
  printf "Starting update of gists' information.\n"

  # check for gist token file existance
  if ! test -r "$DESTDIR/root/.gist"; then
    printf "FATAL ERROR: No gist token file found. Please run 'pbg' again in order to config it.\n"
    exit 1
  fi

  # check for gists' id file
  if ! test -f "$DESTDIR/etc/pbg"; then
    printf "No gists' ids file file found. Creating new gists for them.\n"
    # create new pbg file
    new_pbg
    exit 0
  fi

  # take care of pacman's native packages
  if ! gist -r "$gist_nat" > "/tmp/$PACNAT_FILE"; then
    printf "FATAL ERROR: Failed to read pacman's native packages gist.\n"
    exit 1
  fi

  # check for differences and upload them (if any)
  pacman -Qqen > "/tmp/$PACNAT_FILE.new"
  if ! diff "/tmp/$PACNAT_FILE" "/tmp/$PACNAT_FILE.new" > /dev/null 2>&1; then
    if ! cat "/tmp/$PACNAT_FILE.new" | gist -u "$gist_nat" -f "$PACNAT_FILE"; then
      rm -f "/tmp/$PACNAT_FILE" "/tmp/$PACNAT_FILE.new"
      printf "FATAL ERROR: Failed to update pacman's native packages gist.\n"
      exit 1
    fi
  fi
  # clean used files
  rm -f "/tmp/$PACNAT_FILE" "/tmp/$PACNAT_FILE.new"

  # take care of AUR's packages
  if ! gist -r "$gist_aur" > "/tmp/$AUR_FILE"; then
    printf "FATAL ERROR: Failed to read AUR's packages gist.\n"
    exit 1
  fi

  # check for differences and upload them (if any)
  pacman -Qqem > "/tmp/$AUR_FILE.new"
  if ! diff "/tmp/$AUR_FILE" "/tmp/$AUR_FILE.new" > /dev/null 2>&1; then
    if ! cat "/tmp/$AUR_FILE.new" | gist -u "$gist_aur" -f "$AUR_FILE"; then
      rm -f "/tmp/$AUR_FILE" "/tmp/$AUR_FILE.new"
      printf "FATAL ERROR: Failed to update AUR's packages gist.\n"
      exit 1
    fi
  fi
  # clean used files
  rm -f "/tmp/$AUR_FILE" "/tmp/$AUR_FILE.new"
}


# take care of command line arguments
cargs "$@"

# check existance of the base working program path
if [ "$1" ] && [ ! -d "$1" ]; then
  printf "FATAL ERROR: The given 'DESTDIR' was not found.\n"
  exit 1
fi

# read saved gists id's
if test -r "$DESTDIR/etc/pbg"; then
  gist_nat="$(head -n 1 "$DESTDIR/etc/pbg")"
  gist_aur="$(tail -n 1 "$DESTDIR/etc/pbg")"
fi

# init if necessary
if [ ! "$gist_nat" ] || [ ! "$gist_aur" ]; then
  printf "New init is needed.\n"
  init
else
  # check for fakeroot (script needs real root capabilities)
  if printf "%s" "$LD_LIBRARY_PATH" | grep libfakeroot > /dev/null; then
    is_fakeroot=true
  else
    is_fakeroot=false
  fi
  # update gist contents if root
  if [ "$(id -u)" -eq 0 ] && ! "$is_fakeroot"; then
    update
  fi
fi
